name: Publish Stitch Desktop

on:
  workflow_dispatch:
  push:
    tags:
      - "stitch-desktop@*"

permissions:
  contents: write

defaults:
  run:
    shell: bash

jobs:
  publish:
    runs-on: windows-latest
    steps:
      # SETUP
      - uses: actions/checkout@v3
        with:
          lfs: true
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: corepack enable
      - run: pnpm install --filter=stitch-desktop...
      - run: pwd

      - name: Cache Turbo
        uses: actions/cache@v3
        with:
          key: turbo-stitch-desktop
          path: |
            ~/node_modules
            ~/packages/desktop/bundle/node_modules

      # PREBUILD
      - name: Prepare Cert
        run: |
          echo "${{ secrets.CODESIGN_PFX_BASE64 }}" > cert.base64 && certutil -decode cert.base64 cert.pfx && cp cert.pfx packages/desktop/cert.pfx

      # BUILD
      - name: Build
        run: pnpm turbo run build --only --filter=stitch-desktop... 
        env:
          CODESIGN_PASSWORD: ${{ secrets.CODESIGN_PASSWORD }}
      - name: Set release version
        # This script adds the env var `RELEASE_VERSION`
        run: node scripts/set-release-version.mjs packages/desktop

      - name: Create New Release
        run: gh release create --title "Stitch Desktop v${{env.RELEASE_VERSION}}" stitch-desktop@${{env.RELEASE_VERSION}} packages/desktop/bundle/out/make/squirrel.windows/x64/RELEASES packages/desktop/bundle/out/make/squirrel.windows/x64/Stitch-${{env.RELEASE_VERSION}}-full.nupkg#Nupkg packages/desktop/bundle/out/make/squirrel.windows/x64/StitchSetup.exe#Installer
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      